/*
 * OA2TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
 */
package com.anactualwebsite.www;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://www.an-actual-website.com";

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
