/*
 * OA2TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
 */
package com.anactualwebsite.www;

import com.anactualwebsite.www.controllers.*;
import com.anactualwebsite.www.http.client.HttpClient;

public class OA2TesterClient {
    /**
     * Singleton access to Client controller
     * @return	Returns the APIController instance 
     */
    public APIController getClient() {
        return APIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public OA2TesterClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public OA2TesterClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}