/*
 * OA2TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
 */
package com.anactualwebsite.www.http.request;

/**
 * HTTP methods enumeration
 */
public enum HttpMethod {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE
}
